try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    SKLEARN_AVAILABLE = True
except ImportError:
    print("Warning: scikit-learn not available. LSI functionality will be disabled.")
    SKLEARN_AVAILABLE = False
    # Create dummy functions
    def TfidfVectorizer(*args, **kwargs):
        return None
    def cosine_similarity(*args, **kwargs):
        return None
        

contexts = {
  "Beach Cleanup Drive": "The Beach Cleanup Drive focused on removing trash and pollutants from the coastline. Volunteers participated in collecting various types of waste, including plastics, glass, and cigarette butts. The main objective was to protect marine life by preventing harmful debris from entering the ocean. Participants used gloves and trash bags to safely handle waste, and the event also included sorting recyclables from non-recyclables. Sessions on how waste impacts marine ecosystems were held, emphasizing the importance of clean beaches for both human and animal health.",
  "Tree Planting Campaign": "The Tree Planting Campaign was dedicated to reforesting areas by planting native tree species. Volunteers were guided on how to properly plant and care for trees. The event aimed to combat deforestation, improve air quality, and restore natural habitats. Planting trees also contributes to reducing carbon emissions. In addition, participants learned about the ecological benefits of trees and how they support biodiversity. The activity provided a hands-on experience in environmental restoration and emphasized long-term sustainability.",
  "River Rehabilitation Project": "This event focused on restoring the health of local rivers by cleaning polluted riverbanks and improving water quality. Volunteers worked together to remove waste, plastic, and debris from the river, while also addressing erosion by planting native plants along the edges. The goal was to restore the natural flow of the river and create a healthier habitat for aquatic species. Educational workshops on the importance of healthy rivers were included, and participants learned about the impact of water pollution on ecosystems and local communities.",
  "Mangrove Restoration Activity": "Volunteers participated in restoring mangrove forests by planting young mangrove trees. The event aimed to protect coastal ecosystems by re-establishing mangrove habitats, which help prevent soil erosion and provide shelter for marine life. The activity included learning about the role of mangroves in maintaining biodiversity and mitigating climate change by sequestering carbon. The event emphasized the importance of mangroves in coastal protection, and participants also engaged in cleaning up areas affected by pollution.",
  "Urban Gardening Workshop": "This hands-on workshop focused on teaching participants how to grow plants in urban environments, using limited space. Volunteers learned techniques for creating container gardens, raised beds, and vertical gardens. The goal was to promote sustainable food production and the benefits of growing fresh, healthy produce in cities. The workshop covered topics such as soil health, plant care, and composting, and participants also had the opportunity to build their own small garden. The event helped raise awareness about urban gardening as a solution to food insecurity and environmental impact.",
  "Coastal Waste Audit": "The Coastal Waste Audit was aimed at assessing the types of waste found along the coastline. Volunteers collected and categorized waste materials, focusing on plastics and other pollutants. The activity helped participants understand the scale and impact of coastal pollution, while also providing valuable data for future waste management strategies. The audit process included sorting recyclables from non-recyclables, and volunteers learned about proper disposal methods and recycling practices. The event also included a discussion on how to reduce coastal waste and prevent future pollution.",
  "Recycling Awareness Program": "The Recycling Awareness Program provided education on the importance of recycling and how it reduces waste. Participants learned about different recyclable materials, such as paper, plastic, and metal, and were taught proper sorting techniques. The event emphasized the benefits of recycling in reducing landfill waste, conserving resources, and minimizing environmental harm. Volunteers also participated in a hands-on activity where they sorted waste into recyclables and non-recyclables. The program concluded with discussions on the challenges of recycling and how to improve recycling practices in communities.",
  "Wildlife Conservation Seminar": "The Wildlife Conservation Seminar provided information on the importance of preserving wildlife and their habitats. Experts discussed various species that are endangered and how human activity, such as habitat destruction and poaching, threatens wildlife. Volunteers learned about conservation efforts aimed at protecting wildlife and their environments, as well as how they can contribute to these efforts. The seminar also highlighted the role of biodiversity in maintaining healthy ecosystems. Discussions focused on local and global conservation issues, raising awareness about the need to protect wildlife.",
  "Eco-Brick Making Session": "The Eco-Brick Making Session was focused on teaching participants how to recycle plastic waste by stuffing it into bottles to create eco-bricks. These bricks can be used for building sustainable structures. Volunteers learned about the environmental impacts of plastic waste and how eco-bricks offer a solution by repurposing plastic that would otherwise pollute the environment. The session included hands-on activities, with participants collecting plastic waste, cleaning it, and learning how to properly stuff the bottles. The event also focused on sustainable building techniques and the role of eco-bricks in reducing waste.",
  "Nature Trail Maintenance": "Volunteers worked to clean and maintain nature trails, ensuring that they remain accessible for hikers and other visitors. Tasks included removing debris, fixing trail markers, and repairing any damaged sections of the trail. The goal was to preserve the natural beauty of the trails while ensuring they are safe and easy to navigate. Participants also helped protect surrounding ecosystems by avoiding disturbances to the environment. The event emphasized the importance of maintaining trails to promote outdoor recreation and conservation, and participants were educated about the impacts of overuse on natural areas.",
  "Coral Reef Preservation Drive": "The Coral Reef Preservation Drive focused on protecting coral reefs by cleaning debris and planting coral fragments to restore damaged areas. Volunteers worked together to remove harmful pollutants, such as plastics, from the reef and participated in coral planting activities. The event aimed to protect marine biodiversity by maintaining healthy coral ecosystems, which are crucial for the survival of various marine species. The drive included educational sessions on the threats to coral reefs, such as pollution and climate change, and offered solutions for preserving these fragile ecosystems.",
  "Clean Air Awareness Walk": "The Clean Air Awareness Walk aimed to raise awareness about air pollution and its impact on public health and the environment. Volunteers participated in a walk through urban areas to highlight air quality issues and to promote cleaner, greener alternatives. The event emphasized the importance of reducing air pollution by supporting policies for cleaner energy and sustainable transportation. Educational materials were provided to participants, including information on how air pollution affects both humans and the environment. The walk also served as an advocacy tool for promoting clean air initiatives in the community.",
  "Zero-Waste Lifestyle Workshop": "The Zero-Waste Lifestyle Workshop introduced participants to the principles of reducing waste through mindful consumption and recycling. Volunteers learned how to avoid single-use plastic, compost organic waste, and adopt sustainable habits in everyday life. The event included practical demonstrations on reducing waste at home, at school, and in the community. The workshop highlighted how small changes can make a big impact on the environment and encouraged participants to commit to zero-waste practices. Topics such as the importance of reusing, reducing, and recycling were covered in-depth, with hands-on activities to make learning fun and impactful.",
  "Energy Conservation Seminar": "The Energy Conservation Seminar focused on ways to reduce energy consumption in daily life. The event provided participants with practical tips on how to save energy at home, at work, and in transportation. The seminar covered topics such as the benefits of using energy-efficient appliances, reducing heating and cooling costs, and adopting renewable energy sources. Volunteers also learned about the impact of energy use on the environment, particularly regarding carbon emissions and climate change. The seminar aimed to empower participants with the knowledge to make informed decisions about energy conservation and how to implement these strategies in their own lives.",
  "School Garden Development Project": "The School Garden Development Project involved students and volunteers working together to build and maintain gardens at local schools. The project aimed to create a sustainable space for growing food, flowers, and native plants while teaching students about environmental stewardship and the benefits of gardening. The event included lessons on plant care, composting, and the role of gardens in improving air quality. Participants learned how gardening can foster a sense of community and responsibility while also promoting healthy eating habits.",
  "Sustainable Living Webinar": "The Sustainable Living Webinar aimed to educate participants on adopting eco-friendly practices in daily life. Through online discussions, volunteers learned about topics such as renewable energy, reducing waste, and sustainable food choices. The webinar provided practical tips for reducing environmental impact, including the use of energy-efficient appliances, sustainable transportation, and ways to conserve water. Experts discussed the importance of reducing carbon footprints and how small lifestyle changes can contribute to a larger global impact. The event encouraged participants to become active advocates for sustainable living in their communities.",
  "Community Composting Initiative": "The Community Composting Initiative focused on teaching local communities how to compost organic waste. Volunteers participated in hands-on activities, learning the process of composting food scraps, yard waste, and other biodegradable materials to create nutrient-rich soil. The goal was to reduce the amount of waste sent to landfills and provide an environmentally friendly alternative. Participants learned about the benefits of composting, such as improving soil health, supporting plant growth, and reducing methane emissions from landfills. The event emphasized community collaboration in waste reduction efforts and offered solutions for creating sustainable urban environments.",
  "Ocean Plastic Collection": "The Ocean Plastic Collection event aimed to remove plastic waste from oceans and nearby beaches. Volunteers worked together to collect plastic debris, which poses a significant threat to marine life and ecosystems. The event included educational sessions on the dangers of ocean plastic pollution and how it harms marine species, including ingestion and entanglement. Volunteers learned about the importance of reducing plastic use and participated in efforts to properly dispose of and recycle collected plastics. The ultimate goal was to reduce plastic waste in the ocean, helping to protect aquatic life and maintain cleaner marine environments.",
  "Forest Fire Awareness Campaign": "The Forest Fire Awareness Campaign was designed to educate the public on the causes and prevention of forest fires. Volunteers participated in workshops and discussions about the environmental and economic impacts of wildfires. The event aimed to raise awareness about fire safety, particularly in forested and rural areas, and to encourage community action to prevent wildfires. Participants learned about fire-resistant plants, the importance of clearing dry vegetation, and the role of controlled burns in forest management. The campaign also included information on how individuals can protect their homes and surrounding areas from wildfire risks.",
  "Biodiversity Education Program": "The Biodiversity Education Program focused on educating participants about the importance of biodiversity and how to protect diverse ecosystems. Volunteers attended workshops on local wildlife, plant species, and the role of biodiversity in maintaining ecosystem balance. The event highlighted the threats to biodiversity, such as habitat loss, pollution, and climate change. Participants learned about conservation efforts aimed at preserving endangered species and habitats. The program also provided ways for individuals to contribute to biodiversity protection, both locally and globally, by participating in conservation efforts and making sustainable lifestyle choices.",

  "Healthy Eating Workshop": "The Healthy Eating Workshop provided education on the importance of balanced nutrition and how it contributes to overall well-being. Participants learned about portion control, meal planning, and how to incorporate fruits, vegetables, and whole grains into their daily diets. The event emphasized the benefits of healthy eating in preventing chronic diseases, boosting energy levels, and maintaining a healthy weight. Attendees also participated in interactive cooking demonstrations, where they learned how to prepare simple, nutritious meals. The workshop concluded with a Q&A session on how to make healthier food choices in everyday life.",
  "Mental Health Awareness Campaign": "The Mental Health Awareness Campaign aimed to educate the community about mental health issues and reduce stigma. Participants learned about common mental health conditions, such as anxiety, depression, and stress, and were encouraged to seek help when needed. The event highlighted the importance of mental well-being and promoted available resources for mental health support. Attendees also participated in open discussions and shared personal stories to create a supportive environment. The campaign concluded with a focus on breaking the stigma surrounding mental health and encouraging people to prioritize their mental wellness.",
  "Fitness Challenge Program": "The Fitness Challenge Program encouraged individuals to take part in physical activities such as walking, running, or cycling to improve their fitness levels. Participants learned about the health benefits of regular exercise, including improved cardiovascular health, muscle strength, and mental clarity. The event emphasized the importance of setting personal fitness goals and tracking progress over time. Participants also took part in friendly competitions and group exercises to build motivation and community spirit. The program concluded with tips on how to maintain an active lifestyle and stay committed to fitness goals.",
  "Blood Donation Drive": "The Blood Donation Drive organized a community event to collect blood donations and support local hospitals. Participants learned about the critical need for blood donations and how their contributions could save lives. The event included educational materials on the blood donation process, health screenings, and safety protocols for donors. Volunteers were also encouraged to donate blood and were given the opportunity to ask questions about the donation process. The drive concluded with a celebration of the donors' contributions and a reminder of the ongoing need for blood donations in healthcare settings.",
  "Community Health Screening Event": "The Community Health Screening Event offered free health check-ups to local residents to help detect potential health issues early. Participants were screened for common conditions, such as high blood pressure, diabetes, and cholesterol levels. The event emphasized the importance of regular health check-ups in maintaining good health and preventing chronic diseases. Attendees received personalized health advice from healthcare professionals and were informed about the next steps if any issues were detected. The event concluded with educational sessions on healthy living and how to manage health risks effectively.",
  "Walk for Wellness Campaign": "The Walk for Wellness Campaign encouraged individuals to participate in a community walk to promote physical activity and overall health. Participants learned about the benefits of walking, such as improving cardiovascular health, boosting mood, and enhancing mental clarity. The event emphasized how regular physical activity, like walking, can be easily incorporated into daily routines. Participants also joined group walks and were provided with motivation from fitness coaches. The campaign concluded with an invitation to continue walking regularly and incorporate other forms of exercise into daily life.",
  "Yoga and Meditation Retreat": "The Yoga and Meditation Retreat provided participants with an opportunity to practice mindfulness and reduce stress through yoga and meditation. Participants learned various yoga poses that enhance flexibility and strength, as well as meditation techniques to improve mental clarity and emotional well-being. The retreat emphasized the importance of mental relaxation and how these practices can contribute to a balanced life. Attendees also participated in guided meditation sessions to deepen their mindfulness practice. The retreat concluded with discussions on how to incorporate these practices into daily routines for improved overall health.",
  "Healthy Lifestyle Seminar": "The Healthy Lifestyle Seminar provided information on how to live a healthier life by focusing on diet, exercise, stress management, and sleep. Participants learned about making healthier food choices, setting fitness goals, and managing stress effectively. The seminar emphasized the importance of a balanced approach to health, where physical, mental, and emotional well-being are interconnected. Attendees also participated in practical exercises to help set realistic health goals. The seminar concluded with tips on how to maintain a healthy lifestyle long-term, even with a busy schedule.",
  "Diabetes Prevention Workshop": "The Diabetes Prevention Workshop educated participants on how to reduce the risk of developing diabetes through lifestyle changes. Participants learned about healthy eating habits, including the importance of portion control and reducing sugar intake, as well as the benefits of regular physical activity. The workshop emphasized the importance of maintaining a healthy weight and understanding the risk factors for type 2 diabetes. Attendees also participated in discussions about the early signs of diabetes and how to make lifestyle changes to prevent its onset. The workshop concluded with personalized recommendations for maintaining a diabetes-free lifestyle.",
  "Vaccination Awareness Drive": "The Vaccination Awareness Drive aimed to educate the community about the importance of vaccinations in preventing diseases. Participants learned about vaccines for illnesses like the flu, measles, and COVID-19, and how they protect individuals and the broader community. The event emphasized the role of vaccinations in reducing disease transmission and promoting public health. Attendees also received information on where to get vaccinated and how vaccines contribute to herd immunity. The drive concluded with a discussion on addressing common misconceptions and encouraging widespread vaccination.",
  "Breast Cancer Awareness Walk": "The Breast Cancer Awareness Walk was organized to raise awareness about breast cancer prevention, early detection, and treatment. Participants learned about the importance of self-exams, regular screenings, and the latest advancements in breast cancer research. The event emphasized the role of community support in the fight against cancer and the importance of early detection in improving outcomes. Attendees also participated in a walk to honor survivors and raise funds for breast cancer research. The walk concluded with personal stories from survivors and discussions on how to support those affected by breast cancer.",
  "Physical Activity Promotion Day": "The Physical Activity Promotion Day focused on encouraging people of all ages to engage in physical activities that improve health. Participants learned about the benefits of staying active, such as improved cardiovascular health, weight management, and mental well-being. The event included various physical activities, such as group fitness classes, outdoor games, and fitness challenges. It emphasized the importance of making physical activity a regular part of daily life. The day concluded with motivational talks and tips on how to stay active regardless of age or fitness level.",
  "Tobacco-Free Community Initiative": "The Tobacco-Free Community Initiative aimed to reduce tobacco use in the local community by promoting smoking cessation programs and educating people about the risks of smoking. Participants learned about the harmful effects of tobacco use on health, including its role in causing lung cancer, heart disease, and respiratory issues. The initiative emphasized the importance of quitting smoking and provided resources for those looking to quit. Attendees also engaged in activities such as pledge signing to support a tobacco-free community. The event concluded with success stories from former smokers and tips on how to stay tobacco-free.",
  "Chronic Disease Management Seminar": "The Chronic Disease Management Seminar focused on helping individuals manage chronic conditions such as hypertension, diabetes, and asthma. Participants learned about the impact of chronic diseases on overall health and how to manage them effectively through medication, diet, and exercise. The seminar emphasized the importance of regular check-ups, self-monitoring, and understanding warning signs. Attendees also had the opportunity to ask healthcare professionals questions about managing their conditions. The seminar concluded with tips on maintaining a healthy lifestyle and managing stress for better chronic disease control.",
  "Wellness and Nutrition Education Program": "The Wellness and Nutrition Education Program aimed to provide participants with the knowledge needed to make healthier food choices and improve overall well-being. Participants learned about the key components of a balanced diet, including the benefits of fruits, vegetables, lean proteins, and whole grains. The program emphasized the role of nutrition in maintaining a healthy weight, preventing chronic diseases, and boosting energy levels. Attendees also participated in cooking demonstrations to learn how to prepare nutritious meals. The program concluded with tips on how to incorporate healthy eating habits into everyday life.",
  "Healthy Workplace Campaign": "The Healthy Workplace Campaign encouraged employees to adopt healthier habits within the workplace environment. Participants learned about the importance of physical activity, proper nutrition, and stress management in promoting overall health. The event included activities such as group exercise sessions, healthy snack options, and workshops on managing stress at work. The campaign emphasized creating a supportive workplace culture that prioritizes health and well-being. Attendees also participated in team-building activities and were encouraged to make wellness goals for themselves and their colleagues. The campaign concluded with tips on how to maintain health in a busy work environment.",
  "First Aid and CPR Training Session": "The First Aid and CPR Training Session provided participants with essential life-saving skills. Participants learned how to respond to emergencies, including how to perform CPR, manage bleeding, and assist someone who is choking. The event emphasized the importance of first aid knowledge in protecting both oneself and others in case of accidents or medical emergencies. Attendees also practiced their skills in hands-on exercises to ensure they felt confident in real-life situations. The session concluded with a certification of completion and reminders about the importance of regular training to keep first aid skills up-to-date.",
  "Youth Health and Fitness Expo": "The Youth Health and Fitness Expo focused on educating young people about the importance of physical activity and healthy living. Participants learned about exercise routines, nutrition, and how to create healthy habits from a young age. The event included interactive fitness demonstrations, healthy cooking workshops, and discussions on how to stay active in school and at home. The expo emphasized the long-term benefits of staying fit and maintaining good nutrition. Attendees also participated in fun challenges and activities designed to make fitness enjoyable. The expo concluded with motivational talks from youth fitness influencers and health experts.",
  "Mental Health Support Group Meeting": "The Mental Health Support Group Meeting provided a safe space for individuals to share experiences and receive support for mental health challenges. Participants learned about coping strategies for dealing with anxiety, depression, and other mental health issues. The event emphasized the importance of peer support and open conversations about mental well-being. Attendees shared personal stories and advice on how to manage stress, and also discussed available local resources for mental health assistance. The meeting concluded with a focus on building resilience and encouraging participants to continue seeking support when needed.",
  "Senior Health Advocacy Program": "The Senior Health Advocacy Program focused on addressing the unique health needs of older adults. Participants learned about age-related conditions, such as arthritis, osteoporosis, and cognitive decline, and how to manage these conditions through lifestyle changes. The program emphasized the importance of staying physically active, maintaining a healthy diet, and staying socially engaged for healthy aging. Attendees also received information about healthcare services available to seniors. The program concluded with tips on how to age gracefully and maintain independence while managing health issues.",
  "Women's Health Awareness Day": "The Women's Health Awareness Day aimed to educate women about health issues specific to them, such as reproductive health, breast cancer, osteoporosis, and mental health. Participants learned about preventative measures, early detection, and treatment options for these health concerns. The event included workshops, screenings, and opportunities for women to connect with healthcare providers. The day emphasized the importance of self-care and regular check-ups in maintaining overall health. The event concluded with a focus on empowering women to take charge of their health and well-being.",
  "Sleep Hygiene Awareness Campaign": "The Sleep Hygiene Awareness Campaign aimed to educate the community about the importance of quality sleep for overall health. Participants learned about common sleep disorders, such as insomnia and sleep apnea, and how to improve sleep habits. The campaign emphasized the impact of sleep on physical health, mental well-being, and cognitive function. Attendees were provided with tips on creating a sleep-friendly environment and adopting good sleep practices. The campaign concluded with discussions on how to prioritize sleep and address barriers to getting restful sleep.",
  "Substance Abuse Awareness Seminar": "The Substance Abuse Awareness Seminar focused on educating the community about the dangers of substance abuse and available resources for prevention and recovery. Participants learned about the signs of addiction, the impact of drugs and alcohol on health, and strategies for staying sober. The seminar emphasized the importance of early intervention and seeking help when needed. Attendees also participated in discussions about the stigma surrounding addiction and how to support individuals in recovery. The seminar concluded with a focus on building healthy coping mechanisms and promoting substance-free lifestyles.",

  "Urban Gardening Initiative": "promotes growing food in small urban spaces like rooftops and balconies. Volunteers assist by setting up demonstration gardens and training residents in sustainable urban gardening techniques, such as container gardening, hydroponics, and vertical farming. This initiative encourages the use of limited urban space for food production, helping participants grow fresh produce while fostering a greener city.",
  "Climate Change Awareness Walk": "event aimed at raising awareness about the impact of climate change through a community walk. Participants join together to walk through local areas, symbolizing unity in the fight against climate change and promoting action toward environmental sustainability. The walk serves as a platform to educate the public on the urgent need to address climate change, highlight the importance of reducing carbon footprints, and encourage environmentally responsible behaviors.",
  "Dental Care Outreach Program": "an event focused on providing essential dental care services to underserved communities. This program offers free dental check-ups, cleanings, and educational sessions on maintaining good oral hygiene. Volunteers, including dental professionals, work together to deliver quality care and raise awareness about the importance of regular dental visits and proper oral health practices. The initiative also aims to reduce barriers to dental care, such as cost and access, ensuring that everyone has the opportunity to maintain their oral health",

  "Gender Distribution in Local Government Units": "explores the gender balance in local government offices and administrative roles, with a focus on achieving equal representation in leadership and policy making. Activities include workshops on assessing community needs, advocating for equitable hiring policies, and developing strategies to enhance women’s participation in governance. Feedback evaluation terms include clarity of discussions on gender gaps, relevance of proposed solutions for balanced representation, participant engagement in advocacy workshops, and the effectiveness of activities in addressing gender disparities.",
  "Gender Ratio in Corporate Board Memberships": "analyzes the proportion of male and female executives on corporate boards, emphasizing policies for inclusivity and fair recruitment practices. It highlights success stories and challenges in achieving gender parity within the business world through interactive discussions. Feedback categories involve the quality of insights on corporate gender dynamics, applicability of strategies for inclusivity, diversity of examples shared in presentations, and participant engagement during group discussions.",
  "Male vs. Female Faculty Members in Universities": "discusses the current gender breakdown of faculty members across academic fields. It focuses on mentorship programs for women in academia, addressing biases in faculty hiring, and promoting gender equality in university settings. Feedback evaluation includes the value of mentorship ideas, depth of analysis on hiring biases, applicability of proposed faculty development programs, and relevance of examples shared during presentations.",
  "Gender Representation in Legislative Bodies": "This session examines the presence of women in legislative assemblies, focusing on barriers to entry, the importance of representation in law-making, and policy recommendations for improving gender equality in politics. Feedback phrases might include the strength of proposed solutions to entry barriers, relevance of shared case studies, clarity in explaining legislative challenges, and the effectiveness of policy recommendations presented.",
  "Proportion of Women in Executive Positions": "Focuses on the underrepresentation of women in executive roles and the barriers preventing their advancement in corporate and organizational structures. Discussions cover leadership training, workplace policies for gender equity, and strategies to break the glass ceiling. Feedback phrases include the relevance of discussions on leadership training, effectiveness of proposed strategies for career advancement, and the applicability of case studies to real-world challenges.",
  "Gender Diversity in Research Authorship and Publication": "explores the gender imbalance in academic research, especially in fields dominated by male authors. The discussions include promoting inclusive research practices, mentoring female researchers, and ensuring equitable publication opportunities. Key feedback terms include the clarity of discussions on diversity in research, the applicability of proposed mentorship strategies, and the relevance of ideas to encourage women's contributions to academic publications.",
  "Male vs. Female Participation in Non-Government Organizations (NGOs)": "evaluates the gender distribution in NGOs, focusing on the role of men and women in various capacities, from volunteers to leadership positions. Strategies for encouraging gender parity in NGO operations and increasing female participation in leadership roles will be discussed. Feedback evaluation includes the effectiveness of strategies for increasing female participation, clarity of discussions on gender roles within NGOs, and relevance of examples shared during the event.",
  "Gender Roles in Decision-Making Within Households": "will explore how gender roles influence decision-making within families and households, with discussions on how men and women share power in domestic roles. It will highlight the effects of societal norms on household dynamics and propose ways to promote equal decision-making. Feedback terms might include the effectiveness of strategies to address gender roles in families, relevance of the provided solutions, and participant engagement during discussions.",
  "Volunteerism Rates by Gender Across Sectors": "focuses on the differing rates of volunteerism between men and women, looking at factors that influence volunteer participation across sectors like education, health, and community services. The discussions will aim to understand the motivations behind gender differences and propose strategies to increase volunteerism among both genders. Feedback phrases include the clarity of insights on volunteerism trends, relevance of proposed strategies to increase gender-balanced participation, and effectiveness of activities in encouraging more volunteer work.",
  "Awareness of Cybersecurity Risks by Gender": "examines the differences in awareness and understanding of cybersecurity risks between men and women. Discussions will cover how gender may influence attitudes toward online security, the perceived level of threat, and the behaviors individuals adopt to protect their personal data. Participants will engage in activities that highlight the importance of cybersecurity education for all genders, with a particular focus on addressing any gaps in awareness or action. Feedback evaluation terms include the clarity of discussions on cybersecurity risks, relevance of strategies to improve gender-based awareness, effectiveness of proposed educational approaches, and participant engagement in identifying personal security practices."
}

def LSICosineSimilarityMatch(texts: list[str]):
  if not SKLEARN_AVAILABLE:
    # Return empty similarity scores when scikit-learn is not available
    textContextSimilarity = {}
    for text in texts:
      textContextSimilarity[text] = {}
      for context in contexts.keys():
        textContextSimilarity[text][context] = 0.0
    return textContextSimilarity

  vectorizer = TfidfVectorizer(stop_words='english')
  text_vectors = vectorizer.fit_transform(texts)

  context_vectors = {context: vectorizer.transform([keywords]) for context, keywords in contexts.items()}

  similarities = {}
  for text, vector in zip(texts, text_vectors):
      for context, context_vector in context_vectors.items():
          similarity = cosine_similarity(vector, context_vector).mean()
          similarities.setdefault(text, {})[context] = similarity

  textContextSimilarity = {}
  for text, context_similarities in similarities.items():
      textContextSimilarity[text] = {}
      for context, similarity in context_similarities.items():
          textContextSimilarity[text][context] = float(f"{similarity:.3f}")

  return textContextSimilarity